using System;

[Serializable]
public class Beat
{
    // ── Identity ─────────────────────────────────────────────────────
    public int scene_id;
    public int beat_id;

    // ── Narrative ────────────────────────────────────────────────────
    public string speaker;
    public string dialogue;
    public string action;
    public string emotion;
    public string intent;

    // ── Shot / target metadata ───────────────────────────────────────
    public string shot_type;
    public string camera_angle;
    public string camera_movement;
    public string focus_target;
    public string secondary_target;

    // ── Timing ───────────────────────────────────────────────────────
    public float duration;
    public string transition;

    // ════════════════════════════════════════════════════════════════
    // CAMERA POSITION / ROTATION
    // These are direct values generated by the AI Director Brain.
    // Unity should use them directly when the flags are enabled.
    // ════════════════════════════════════════════════════════════════

    // ── Camera exact position in world space ─────────────────────────
    public float camera_position_x;
    public float camera_position_y;
    public float camera_position_z;
    public bool use_exact_camera_position;

    // ── Camera exact rotation in world Euler angles ──────────────────
    public float camera_rotation_x;
    public float camera_rotation_y;
    public float camera_rotation_z;
    public bool use_exact_camera_rotation;

    // ── Explicit camera binding targets ──────────────────────────────
    public string camera_follow_target;
    public string camera_look_at_target;

    // ── Camera offset relative to follow target ──────────────────────
    public float camera_offset_x;
    public float camera_offset_y;
    public float camera_offset_z;
    public bool use_exact_camera_offset;

    // ── Lens / motion parameters ─────────────────────────────────────
    public float fov_override;
    public float orbit_speed_override;
    public float dolly_speed_override;
    public float pan_speed_override;

    // ════════════════════════════════════════════════════════════════
    // CHARACTER / ANIMATION
    // ════════════════════════════════════════════════════════════════

    // ── Optional explicit animation name generated by AI ─────────────
    public string animation_name;

    // ── Optional movement speed generated by AI ──────────────────────
    public float move_speed;

    // ── Character start position in world space ──────────────────────
    public float char_start_x;
    public float char_start_y;
    public float char_start_z;
    public bool use_char_start_position;

    // ── Character end / destination position in world space ──────────
    public float char_end_x;
    public float char_end_y;
    public float char_end_z;
    public bool use_char_end_position;

    // ── Character facing direction as Euler Y degrees ────────────────
    public float char_facing_y;
    public bool use_char_facing;
}